common:
  d_hidden: 256
  n_mels: 80

transformer:
  d_hidden: 256
  n_heads: 4
  n_encoder_layers: 4
  n_decoder_layers: 4
  d_feedforward: 256
  dropout: 0.1

prenet:
  encoder:
    n_phonemes: 120
    n_convolutions: 3
    kernel_size: 3
  decoder:
    sizes:
      - 256
      - 256



decoder:
  mel_output:
    n_mels: 80
  stop_token:
    d_hidden: 256

positional_encoding:
  max_seq_len: 1024
  d_hidden: 256

postnet:
  kernel_size: 5
  n_convolutions: 5
  d_hidden: 1024
